### ISSUE TITLE
add -F option to 'bd run' so you can directly tail the logs for the build you start

### ISSUE THREAD

**Issue by gabemontero** [shipwright-io/cli#10]
I suggested this to @alicerum during some of her recently merged PRs

I then learned that based on prior planning, that was declared out of scope for her recently completed set of work.

Per conversation with @adambkaplan I'm opening an issue to track this.

Feels to me like a good way for me to tinker with some code, get familiar.

FYI, we have something very analogous to this with openshift builds, namely `oc start-build -F`

**Comment by adambkaplan** [comment]
This feature would be useful and should be included in our GA backlog. If folks in the community wish to contribute this feature before then, they are free to do so.

**Comment by gabemontero** [comment]
The itch to code on shipwright got to the point where I started hacking on this today.  I have a change ready which I'll start unit testing tomorrow.  If all goes well I'll have a PR up shortly after.
