### ISSUE TITLE
Create a LocalCopy Build

### ISSUE THREAD

**Issue by otaviof** [shipwright-io/cli#100]
A `Build` resource may have `.spec.sources[]` with `LocalCopy` defined, in this case we should allow `shp build create` without requiring `--source-url`.

Perhaps we should have a toggle flag for this behavior.

/cc @qu1queee

**Comment by SaschaSchwarze0** [comment]
From grooming:

- on `shp build create`, today, `source-url` is a mandatory field which is not relevant for local sources where you then do `shp build upload`
- -> should `source-url` be optional ? (There are other use cases where there is no source needed, like a strategy that does a rebase) Could be with a warning.

Conclusion: make `source-url` optional.
