### ISSUE TITLE
Bump go modules and CI to go v1.19

### ISSUE THREAD

**Issue by qu1queee** [shipwright-io/cli#154]
Per grooming, no objections on moving from go v1.18 to v1.19(latest stable). This requires two changes:

- go.mod
- CI(any Github action using a go runtime)

**Comment by bvdwalt** [comment]
I think this issue can be closed @qu1queee. I stumbled upon it thinking I could do it.

**Comment by liangyuanpeng** [comment]
I believe that this issue should be closed. 

/cc @qu1queee

**Comment by qu1queee** [comment]
thank you!

/close
