### ISSUE TITLE
Define root command and initial subcommands

### ISSUE THREAD

**Issue by qu1queee** [shipwright-io/cli#2]
_Idea_:

As a developer I would like to have an initial CLI that have a well defined root and initial subcommands, and the proper documentation on how to use them.

The root command should:
- have a short and long _ad hoc_ description
- should be able to invoke a _build_ subcommand and a _buildrun_ subcommand.
- should be able to catch errors happening from the subcommands and return them to the user (_e.g. exitCode 1_)

The subcommands should:
- have a `build` subcommand that can perform CRUD operations on Shipwright Build CRDs
- have a `build run` subcommand that can perform CRUD operations on Shipwright BuildRun CRDs
- be able to propagate errors to the parent root cmd

The documentation should:
- Provide examples of usage
- Enhance the README

_Acceptance_Criteria_:

Provide the above via a PR.

_Note_: Additionally would be nice to have a well define Makefile target that can build a binary for different platforms

**Comment by qu1queee** [comment]
I would be working on the above via https://github.com/qu1queee/cli/tree/qu1queee/subcmds and then provide a PR for feedback.

**Comment by qu1queee** [comment]
We have a call today around this issue and in general on the CLI design, these are the meeting minutes ( fyi @otaviof , @HeavyWombat , Alice Rum):

Meeting minutes (16/Feb/2021)
- We went through https://drive.google.com/file/d/1dO2uYdhHdz8Qy4h3o5ytDinkbAVvpp6B/view?usp=sharing , which provides some insights on the existing CLI [EP](https://github.com/shipwright-io/build/blob/master/docs/proposals/cli.md) and examples of the existing IBM Code Engine CLI.
- From the options listed [EP](https://github.com/shipwright-io/build/blob/master/docs/proposals/cli.md) , option 2 is the more appealing one.
- As seen in the document, we showed examples on how the IBM Code Engine CLI operates on Build/BuildRuns.
- For shp, we should have a single parent command for retrieving logs. At the same level of “build” and “buildrun”.
- In Code Engine CLI, there is a “ce buildrun submit” subcommand, which starts a buildRun. We think this is a good naming for shp (“submit”)
- For secrets management, we should have a single parent command for retrieving logs. At the same level of “build” and “buildrun”. In Code Engine CLI, they have a single command for github secrets (called “repo”) and another one for registry secrets (called “registry”). We are not sure what would be the best approach for shp.
- From @otaviof , we should have a well define interface for all subcommands. Example: https://github.com/otaviof/shp/blob/master/pkg/shp/cmd/interface.go
- We discussed the need of having another root command, that can abstract the complexity for users of building an image via multiple commands. Something like `shp init`, that generates a container image(creates both build and buildrun under the hood) and that does not uses `verbs`, but only a `resource` and multiple flags.

**Comment by adambkaplan** [comment]
This has been implemented, however the documentation only exists via the command line.
This should also exist in GitHub as markdown.

**Comment by otaviof** [comment]
> This has been implemented, however the documentation only exists via the command line. This should also exist in GitHub as markdown.

With #94 in place, we have the same documentation in markdown as well. May we close this? /cc @qu1queee

**Comment by qu1queee** [comment]
yes, let close this one.
