### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/cli#21]
As is the case with the build controller, the command line should also have an automated release process driven by GitHub Actions.

The release should include the following:

- [ ] Cross compiled binaries
- [ ] Checksums for binaries
- [ ] Generated release notes
- [ ] _Long term_: Signed binaries for respective platforms (macOS and Windows in particular).

**Comment by otaviof** [comment]
That might be a duplicate of #23, for the record.

**Comment by adambkaplan** [comment]
/close

Let's run with the GoReleaser approach in #23
