### ISSUE TITLE
[SHIP-0038] Use Release Branches for Releasing

### ISSUE THREAD

**Issue by adambkaplan** [shipwright-io/cli#238]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem or use-case? Please describe.

Per [SHIP-0038](https://github.com/shipwright-io/community/blob/main/ships/0038-release-branching-backports.md), we are changing our release process to ship official releases from a release branch, rather than from main.

### Describe the solution that you would like.

* CI and release scripts can be run on a release branch (with release-v* pattern)
* Release workflows must use an appropriate release branch and/or git reference (cannot blindly use latest commit from main)
* Tagging should be part of the release script process (currently must be done manually by a maintainer).

### Describe alternatives you have considered.

See [SHIP-0038](https://github.com/shipwright-io/community/blob/main/ships/0038-release-branching-backports.md) for discussion

### Anything else?

Part of https://github.com/shipwright-io/community/issues/85

**Comment by qu1queee** [comment]
@adambkaplan how do we handle this item, should this be linked to a milestone?

**Comment by adambkaplan** [comment]
/close

Released v0.13.0 with the branching mechanism!
