### ISSUE TITLE
[FEATURE] Improved Error Messaging for Nonexistent Namespaces in Shipwright CLI

### ISSUE THREAD

**Issue by jitendar-singh** [shipwright-io/cli#244]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem or use-case? Please describe.

Currently, when a user specifies a namespace that either doesn't exist or lacks builds/build runs, the CLI returns only the field headers without any contextual message. This can lead to confusion and frustration for users who are expecting feedback regarding the absence of builds or build runs in the specified namespace.

### Describe the solution that you would like.

To enhance the user experience and provide clearer feedback, I would like to propose the implementation of descriptive error messages in such scenarios. For example:

- If the specified namespace does not exist:
"Error: Namespace 'xyz' not found. Please ensure that the namespace exists and try again."

- If the specified namespace exists but contains no builds:
"No builds found in namespace 'xyz'. Please initiate a build or verify the namespace."

- If the specified namespace exists but contains no build runs:
"No build runs found in namespace 'xyz'. Please start a build run or check the namespace."

### Anything else?

```
jitsingh@jitsingh-mac  ~/Downloads  shp build list -n builds-example (This project doesnt exist)
NAME	OUTPUT	STATUS
```

```
 jitsingh@jitsingh-mac  ~/Downloads  shp build list -n build-examples
NAME			OUTPUT										STATUS
buildah-golang-build	quay.io/sunnyconcise/shipwright-example:latest					all validations succeeded
s2i-nodejs-build	image-registry.openshift-image-registry.svc:5000/build-examples/nodejs-ex	all validations succeeded

```
 ```
jitsingh@jitsingh-mac  ~/Downloads  shp buildrun list -n build-examples
NAME				STATUS		AGE
buildah-golang-buildrun		Succeeded	1d
s2i-nodejs-buildrun		Succeeded	1d

```
```
 jitsingh@jitsingh-mac  ~/Downloads  shp buildrun list -n build-example ((This project doesnt exist)
NAME	STATUS	AGE
```

**Comment by qu1queee** [comment]
Discussed during refinement, we will look for help in Slack or similar.

**Comment by Adarsh-jaiss** [comment]
Hey @qu1queee , I would love to work on this issue

**Comment by Adarsh-jaiss** [comment]
Hey @qu1queee , I would love to work on this issue

**Comment by Adarsh-jaiss** [comment]
- Hey @qu1queee , while fixing the bug, i'm not able to find the shipwright API for fetching the namespaces. Can you please help me out on this

**Comment by Adarsh-jaiss** [comment]
hey @qu1queee, here's the PR. please review it!!
