### ISSUE TITLE
Command line flags for build and build run aren't propogated to the build or buildRun object

### ISSUE THREAD

**Issue by coreydaley** [shipwright-io/cli#26]
It seems that specifying any of the command line options for `shp build` or `shp build run` (there may be more affected) are not propagated to the underlying objects.

**Comment by otaviof** [comment]
Troubleshooting this issue, I think it's related to the pointer to another pointer, like for instance [here](https://github.com/shipwright-io/cli/blob/6b5d007c1050df6abf1421275b995b6da4a4edbe/pkg/shp/flags/buildrun.go#L23). When dealing with a pointer-to-string, it does work as expected:

```go
func TestStringPointerValue(t *testing.T) {
	g := gomega.NewGomegaWithT(t)

	flagName := "flag"
	value := "value"
	targetStr := "string"

	cmd := &cobra.Command{}
	flags := cmd.PersistentFlags()
	flags.Var(NewStringPointerValue(&targetStr), flagName, "")

	err := flags.Set(flagName, value)
	g.Expect(err).To(o.BeNil())

	v, err := flags.GetString(flagName)
	g.Expect(err).To(o.BeNil())
	g.Expect(value).To(o.Equal(v))
}
```
