### ISSUE TITLE
As a CLI user I would like to list the images I build

### ISSUE THREAD

**Issue by qu1queee** [shipwright-io/cli#3]
I´m wondering if it would be a nice sub command to allow users to list all the images they build. Something like:

`shp images list`

that gives you a list of:

`<image name> <sha>`

the above list will be generated by all the existing buildruns in a particular k8s namespace.

Looking for feedback.

**Comment by otaviof** [comment]
Interesting idea, @qu1queee! And how could we correlate`BuildRun` and `Build` objects with the images being listed?

**Comment by adambkaplan** [comment]
/close

Closing this so we can move the discussion to community#8
