### ISSUE TITLE
The `name` argument for `shp buildrun create` could be optional

### ISSUE THREAD

**Issue by akram** [shipwright-io/cli#50]
This is a usability discussion:
Should  the `name` argument for `shp buildrun create` be optional ? 

e.g:
```
$ shp buildrun create --buildref-name=my-build
buildrun my-build-3214545124 has been created
```
If the name is not passed as a parameter, we could pass the shipwright-client a `generatedName` value which is based on `--buildref-name` . This way we can have a more consistent behaviour with the old `oc start-build` command but also with kubernetes dependent object creation style.

For compatibility reason we can keep the `name` as a possible parameter or we can even think at removing it.
What do you think?

**Comment by otaviof** [comment]
I think we also need to take in consideration the `build run` sub-command. As in:

```bash
shp build run <build-name>
```

In other words, it allows users to "run" a `Build` directly, [via its name](https://github.com/shipwright-io/cli/blob/14e977b3bb690ae8587d288f4795d012b6f3aa45/pkg/shp/cmd/build/run.go#L59). Here, the [generate-name will take place](https://github.com/shipwright-io/cli/blob/14e977b3bb690ae8587d288f4795d012b6f3aa45/pkg/shp/cmd/build/run.go#L155), and based on the informed build name.

And then, on the `buildrun create`, I think we should allow the users to define the actual `BuildRun` name *about to be created*. As in:

```bash
shp buildrun create <buildrun-name> --buildref-name=<build-name>
```

Thus, the flag `--buildref-name` is mandatory.

Putting those sub-commands side-by-side, I think we can cover two possible use-cases elegantly. As in, the user wants to *run a build*, versus the user wants to *create (a specific) `BuildRun` object*.

Does it make sense?

**Comment by akram** [comment]
I like the `shp build run <build-name>` approach. But I am questioning also why would a user want to create a `buildrun` with a specific name; that name being potentially totally different from the `build` name?


`shp build run <build-name>` would also be `shp buildrun create --buildref-name=<build-name>` synonims at the end. So, having one of them should be sufficient.

**Comment by alicerum** [comment]
I want to +1 to what @otaviof said.
To me `build run` references to the `Build` object I would like to run. And I would try to pass the `Build` name there and expect it to be run and all the additional stuff to be generated automatically.
`buildrun create` is more technical, it is about the actual `BuildRun` object, and there user would be able to set the name of the `BuildRun`.

**Comment by adambkaplan** [comment]
/close

We think `shp build run` is the experience we want to drive users towards. `shp buildrun create` is reserved for more imperative use cases. With the current work being done with "inline Build" objects in the `BuildRun` API, I can see us adding more flag options so a full `Build` specification can be set with CLI flags.
