### ISSUE TITLE
shp build run --follow hangs if BuildRun fails to start

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/cli#53]
`shp build run --follow` is my favorite command, but, it actually hangs if a pod never gets created. It should also watch the BuildRun status. If that completes with a failure, then it should also return.

**Comment by gabemontero** [comment]
> As an earlier indicator of where I'm headed with the "pod never gets created" piece with just vanilla k8s suppport (again watching buildrun and/or taskrun for now), I leaning toward
> 
>     * make sure any context deadline specified in the kubeconfig context that is passed in `shp` via `--context` is honored
> 
>     * make sure the k8s `--request-timeout` is honored
> 

this is *NOT* currently being honored  ... minimally adding it for --follow but we probably want to use this more pervasively
