### ISSUE TITLE
Use golangci-lint in favor of running individual tools

### ISSUE THREAD

**Issue by SaschaSchwarze0** [shipwright-io/cli#77]
In [verify.yaml](https://github.com/shipwright-io/cli/blob/main/.github/workflows/verify.yaml), we today run a set of different tools. As decided in the community meeting from [2021/11/22](https://github.com/shipwright-io/community/issues/42#issuecomment-975581815), we should start to use [golangci-lint](https://golangci-lint.run/) and get rid of many of them.

Sibling issues:

- https://github.com/shipwright-io/build/issues/948
- https://github.com/shipwright-io/operator/issues/35

**Comment by vancanhuit** [comment]
Hi,
As a new contributor, can I take this one?
