### ISSUE TITLE
Can't tail buildruns. (buildrun create, buildrun logs)

### ISSUE THREAD

**Issue by stobias123** [shipwright-io/cli#80]
I might be unclear on proper usage of the CLI, but I have been creating my builds like so...

```shell
shp buildrun create -n build --buildref-name foo \
  --output-image gcr.io/foo/bar:${{ steps.date.outputs.date }}-${GITHUB_SHA::4} \
  foo-${{ steps.date.outputs.date }}-${GITHUB_SHA::4}-${{github.run_attempt }}
```

and then trying to tail logs. 

[Some searching](https://github.com/shipwright-io/cli/issues/10) led me to find that I can follow w/ `shp build run -F` which is a little un-intuative.

Would love to be able to follow logs with `shp buildrun logs` or `shp buildrun create` similar to how you can with `shp build run`

**Comment by gabemontero** [comment]
Adding a `-F` flag to `shp buildrun logs` to allow for log following for that makes sense to me and should be a straight forward addition to the existing code base.

If I cannot get to it myself, I would certainly approve / be willing to review such a change.
