### ISSUE TITLE
Excessive amount of flags

### ISSUE THREAD

**Issue by qu1queee** [shipwright-io/cli#99]
## Idea

I'm currently playing with cli and one of the things that make I  tedious to use, it is the amount of `global flags`.  

## Rational

I feel obliged to read the flags usage before triggering a subcommand, and the > 25 global flags just put me at the edge of not using it.

## Goal

I would like to understand the reason behind this. I would favor an approach where they are brought to a minimum and I'm happy to contribute this.

**Comment by otaviof** [comment]
I think you have a good point here, @qu1queee 👍 Let me share some insights on this subject, please.

First of all, the reason we have so many global flags comes from this construction:

https://github.com/shipwright-io/cli/blob/47939df5fca9171125ee20421d37d7f544b8c132/pkg/shp/params/params.go#L36-L39

However, with a close inspection of what's in use, we only find [namespace](https://github.com/shipwright-io/cli/blob/47939df5fca9171125ee20421d37d7f544b8c132/pkg/shp/params/params.go#L113-L123) and [timeout](https://github.com/shipwright-io/cli/blob/47939df5fca9171125ee20421d37d7f544b8c132/pkg/shp/params/params.go#L79-L90) being directly referenced.

While reusing `genericclioptions.ConfigFlags` was handy to get the project started, I also think we could reduce the amount of flags. As my initial though, I think the may only need the following global flags:

- `--kube-config`: typecal path to Kubernetes client configuration file, by default `~/.kube/config`
- `--namespace`: defines the target namespace, default empty so it uses what's in the client current scope
- `--timeout`: to rule out request timeout against the API-Server, where the default should be the same than we are currently using.

**Comment by SaschaSchwarze0** [comment]
From grooming:

- ideas: do not show all options
- question: do we still want `shp` to be(come) a `kubectl` plugin
- `tkn` does not show these flags
- we could filter the options also
- mostly need `kubeconfig` and `namespace`, also `timeout` but likely not the rest

Conclusion: still support genericclioptions, but only show the prominent options in the `help`.
